repo_url: https://github.com/orgs/DailyQuest-project/repositories
repo_name: Daily Quest 

site_name: Daily Quest - Documentação
site_description: Documentação do Projeto Daily Quest
site_author: Marcos V Marinho

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png

  palette:
    # Modo claro (default)
    - scheme: default
      toggle: 
        icon: material/toggle-switch-off-outline
        name: Mudar para modo escuro
      primary: green
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Mudar para modo claro
      primary: green
  
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy

nav:
  - Home: index.md
  - Product Backlog: 
    - Backlog: backlog.md
    - Critérios de Aceite: criterios.md
  - Diagrama de Classes: diagrama.md
  - Protótipo de Alta Fidelidade: prototipo.md
  - Documentação do Banco De Dados: banco.md